In [2]:
import pandas as pd

data = {
    "name": ["Ali", "Ahmed", "Sara", "Hamza", "Ayesha",
             "Usman", "Zain", "Bilal", "Hira", "Daniyal"],
    "department": ["CS", "IT", "CS", "SE", "IT",
                   "CS", "SE", "IT", "CS", "SE"],
    "gender": ["M", "M", "F", "M", "F",
               "M", "M", "M", "F", "M"],
    "marks": [85, 72, 91, 65, 88, 76, 95, 72, 89, 81],
    "attendance": [90, 85, 95, 70, 92, 88, 98, 80, 94, 86],
    "city": ["Lahore", "Karachi", "Lahore", "Islamabad",
             "Lahore", "Karachi", "Multan", "Lahore",
             "Islamabad", "Karachi"]
}

df = pd.DataFrame(data)

In [3]:
df['marks'].median()

83.0

In [4]:
df.describe()

           marks  attendance
count  10.000000    10.00000
mean   81.400000    87.80000
std     9.811558     8.20298
min    65.000000    70.00000
25%    73.000000    85.25000
50%    83.000000    89.00000
75%    88.750000    93.50000
max    95.000000    98.00000

In [5]:
df['department'].value_counts()

department
CS    4
IT    3
SE    3
Name: count, dtype: int64

In [6]:
df['department'].value_counts(normalize=True)*100

department
CS    40.0
IT    30.0
SE    30.0
Name: proportion, dtype: float64

In [7]:
df

      name department gender  marks  attendance       city
0      Ali         CS      M     85          90     Lahore
1    Ahmed         IT      M     72          85    Karachi
2     Sara         CS      F     91          95     Lahore
3    Hamza         SE      M     65          70  Islamabad
4   Ayesha         IT      F     88          92     Lahore
5    Usman         CS      M     76          88    Karachi
6     Zain         SE      M     95          98     Multan
7    Bilal         IT      M     72          80     Lahore
8     Hira         CS      F     89          94  Islamabad
9  Daniyal         SE      M     81          86    Karachi

In [8]:
std_dep = df.groupby(['department'])

In [11]:
std_dep.head(1)

    name department gender  marks  attendance       city
0    Ali         CS      M     85          90     Lahore
1  Ahmed         IT      M     72          85    Karachi
3  Hamza         SE      M     65          70  Islamabad

In [14]:
std_dep['marks'].mean()

department
CS    85.250000
IT    77.333333
SE    80.333333
Name: marks, dtype: float64

In [21]:
std_dep.get_group('CS')

/tmp/ipykernel_5118/1466959325.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  std_dep.get_group('CS')

    name department gender  marks  attendance       city
0    Ali         CS      M     85          90     Lahore
2   Sara         CS      F     91          95     Lahore
5  Usman         CS      M     76          88    Karachi
8   Hira         CS      F     89          94  Islamabad

In [25]:
std_grp = df.groupby("department")

In [34]:
result = std_grp.agg(
    avg_marks=('marks', 'mean'),
    max_marks=('marks', 'max'),
    avg_attendance=('attendance', 'mean')
)
display(result)

            avg_marks  max_marks  avg_attendance
department
CS          85.250000         91       91.750000
IT          77.333333         88       85.666667
SE          80.333333         95       84.666667

In [35]:
std_grp.head()

      name department gender  marks  attendance       city
0      Ali         CS      M     85          90     Lahore
1    Ahmed         IT      M     72          85    Karachi
2     Sara         CS      F     91          95     Lahore
3    Hamza         SE      M     65          70  Islamabad
4   Ayesha         IT      F     88          92     Lahore
5    Usman         CS      M     76          88    Karachi
6     Zain         SE      M     95          98     Multan
7    Bilal         IT      M     72          80     Lahore
8     Hira         CS      F     89          94  Islamabad
9  Daniyal         SE      M     81          86    Karachi

In [37]:
res = std_grp.agg(
    Total_Students = ('name','count'),
    Median_Marks = ('marks','median'),
    Min_Marks = ('marks','min')
)
display(res)

            Total_Students  Median_Marks  Min_Marks
department
CS                       4          87.0         76
IT                       3          72.0         72
SE                       3          81.0         65

In [38]:
df

      name department gender  marks  attendance       city
0      Ali         CS      M     85          90     Lahore
1    Ahmed         IT      M     72          85    Karachi
2     Sara         CS      F     91          95     Lahore
3    Hamza         SE      M     65          70  Islamabad
4   Ayesha         IT      F     88          92     Lahore
5    Usman         CS      M     76          88    Karachi
6     Zain         SE      M     95          98     Multan
7    Bilal         IT      M     72          80     Lahore
8     Hira         CS      F     89          94  Islamabad
9  Daniyal         SE      M     81          86    Karachi

In [39]:
def perf(x):
  if x >= 85:
    return 'Excellent'
  if x >=70 and x < 85:
    return 'Good'
  else:
    return 'Need Improvement'

In [41]:
df['performance'] = df['marks'].apply(perf)

In [42]:
df

      name department gender  marks  attendance       city       performance
0      Ali         CS      M     85          90     Lahore         Excellent
1    Ahmed         IT      M     72          85    Karachi              Good
2     Sara         CS      F     91          95     Lahore         Excellent
3    Hamza         SE      M     65          70  Islamabad  Need Improvement
4   Ayesha         IT      F     88          92     Lahore         Excellent
5    Usman         CS      M     76          88    Karachi              Good
6     Zain         SE      M     95          98     Multan         Excellent
7    Bilal         IT      M     72          80     Lahore              Good
8     Hira         CS      F     89          94  Islamabad         Excellent
9  Daniyal         SE      M     81          86    Karachi              Good

In [49]:
filt = df['name'].str.lower().str.contains('a')
df[filt]

      name department gender  marks  attendance       city       performance
0      Ali         CS      M     85          90     Lahore         Excellent
1    Ahmed         IT      M     72          85    Karachi              Good
2     Sara         CS      F     91          95     Lahore         Excellent
3    Hamza         SE      M     65          70  Islamabad  Need Improvement
4   Ayesha         IT      F     88          92     Lahore         Excellent
5    Usman         CS      M     76          88    Karachi              Good
6     Zain         SE      M     95          98     Multan         Excellent
7    Bilal         IT      M     72          80     Lahore              Good
8     Hira         CS      F     89          94  Islamabad         Excellent
9  Daniyal         SE      M     81          86    Karachi              Good

In [51]:
df[df['name'].apply(lambda x: x.lower()).str.contains('a')]

      name department gender  marks  attendance       city       performance
0      Ali         CS      M     85          90     Lahore         Excellent
1    Ahmed         IT      M     72          85    Karachi              Good
2     Sara         CS      F     91          95     Lahore         Excellent
3    Hamza         SE      M     65          70  Islamabad  Need Improvement
4   Ayesha         IT      F     88          92     Lahore         Excellent
5    Usman         CS      M     76          88    Karachi              Good
6     Zain         SE      M     95          98     Multan         Excellent
7    Bilal         IT      M     72          80     Lahore              Good
8     Hira         CS      F     89          94  Islamabad         Excellent
9  Daniyal         SE      M     81          86    Karachi              Good

In [52]:
departments = pd.Series(
    [80, 75, 78],
    index=["CS", "IT", "SE"],
    name="target_marks"
)

minimum_attendance = pd.Series(
    [85, 80, 82],
    index=["CS", "IT", "SE"],
    name="minimum_attendance"
)

In [61]:
newdf = pd.concat([departments, minimum_attendance], axis = 1)

In [62]:
newdf

    target_marks  minimum_attendance
CS            80                  85
IT            75                  80
SE            78                  82