<a href="https://colab.research.google.com/github/MuhammadRayasat/Python_Pandas/blob/main/Lecture_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {
    "first_name": ["Ali", "Ahmed", "Sara", "Hamza", "Ayesha", "Usman", "Zain"],
    "last_name": ["Khan", "Malik", "Raza", "Ali", "Sheikh", "Butt", "Ahmed"],
    "age": [18, 20, 19, 21, 18, 22, 20],
    "city": ["Lahore", "Karachi", "Lahore", "Islamabad", "Lahore", "Karachi", "Multan"],
    "marks": [85, 72, 91, 65, 88, 76, 95]
}

df = pd.DataFrame(data)

In [ ]:
df["full_name"] = df["first_name"] + " " + df["last_name"] #Create a new column

In [ ]:
df

  first_name last_name  age       city  marks      full_name
0        Ali      Khan   18     Lahore     85       Ali Khan
1      Ahmed     Malik   20    Karachi     72    Ahmed Malik
2       Sara      Raza   19     Lahore     91      Sara Raza
3      Hamza       Ali   21  Islamabad     65      Hamza Ali
4     Ayesha    Sheikh   18     Lahore     88  Ayesha Sheikh
5      Usman      Butt   22    Karachi     76     Usman Butt
6       Zain     Ahmed   20     Multan     95     Zain Ahmed

In [ ]:
df['result'] = df['marks'].apply(lambda x: 'Pass' if x >= 50 else 'Fail') #Q2

In [ ]:
df

  first_name last_name  age       city  marks      full_name result
0        Ali      Khan   18     Lahore     85       Ali Khan   Pass
1      Ahmed     Malik   20    Karachi     72    Ahmed Malik   Pass
2       Sara      Raza   19     Lahore     91      Sara Raza   Pass
3      Hamza       Ali   21  Islamabad     65      Hamza Ali   Pass
4     Ayesha    Sheikh   18     Lahore     88  Ayesha Sheikh   Pass
5      Usman      Butt   22    Karachi     76     Usman Butt   Pass
6       Zain     Ahmed   20     Multan     95     Zain Ahmed   Pass

In [ ]:
df['age_group'] = df['age'].apply(lambda x: 'Teen' if x >= 20 else 'Adult')

In [ ]:
df

  first_name last_name  age       city  marks      full_name result age_group
0        Ali      Khan   18     Lahore     85       Ali Khan   Pass     Adult
1      Ahmed     Malik   20    Karachi     72    Ahmed Malik   Pass      Teen
2       Sara      Raza   19     Lahore     91      Sara Raza   Pass     Adult
3      Hamza       Ali   21  Islamabad     65      Hamza Ali   Pass      Teen
4     Ayesha    Sheikh   18     Lahore     88  Ayesha Sheikh   Pass     Adult
5      Usman      Butt   22    Karachi     76     Usman Butt   Pass      Teen
6       Zain     Ahmed   20     Multan     95     Zain Ahmed   Pass      Teen

In [ ]:
df[['first','last']]=df['full_name'].str.split(" ", expand=True) #Q3

In [ ]:
df

,first_name,last_name,age,city,marks,full_name,result,age_group,first,last
0,Ali,Khan,18,Lahore,85,Ali Khan,Pass,Adult,Ali,Khan
1,Ahmed,Malik,20,Karachi,72,Ahmed Malik,Pass,Teen,Ahmed,Malik
2,Sara,Raza,19,Lahore,91,Sara Raza,Pass,Adult,Sara,Raza
3,Hamza,Ali,21,Islamabad,65,Hamza Ali,Pass,Teen,Hamza,Ali
4,Ayesha,Sheikh,18,Lahore,88,Ayesha Sheikh,Pass,Adult,Ayesha,Sheikh
5,Usman,Butt,22,Karachi,76,Usman Butt,Pass,Teen,Usman,Butt
6,Zain,Ahmed,20,Multan,95,Zain Ahmed,Pass,Teen,Zain,Ahmed

In [ ]:
new_students = pd.DataFrame({
    "first_name": ["Bilal", "Hassan"],
    "last_name": ["Ahmed", "Rauf"],
    "age": [19, 21],
    "city": ["Lahore", "Faisalabad"],
    "marks": [82, 74]
})

In [ ]:
df = pd.concat([df, new_students], ignore_index=True)

In [ ]:
df

,first_name,last_name,age,city,marks,full_name,result,age_group,first,last
0,Ali,Khan,18,Lahore,85,Ali Khan,Pass,Adult,Ali,Khan
1,Ahmed,Malik,20,Karachi,72,Ahmed Malik,Pass,Teen,Ahmed,Malik
2,Sara,Raza,19,Lahore,91,Sara Raza,Pass,Adult,Sara,Raza
3,Hamza,Ali,21,Islamabad,65,Hamza Ali,Pass,Teen,Hamza,Ali
4,Ayesha,Sheikh,18,Lahore,88,Ayesha Sheikh,Pass,Adult,Ayesha,Sheikh
5,Usman,Butt,22,Karachi,76,Usman Butt,Pass,Teen,Usman,Butt
6,Zain,Ahmed,20,Multan,95,Zain Ahmed,Pass,Teen,Zain,Ahmed
7,Bilal,Ahmed,19,Lahore,82,NaN,NaN,NaN,NaN,NaN
8,Hassan,Rauf,21,Faisalabad,74,NaN,NaN,NaN,NaN,NaN

In [ ]:
filt=df['first_name'] == 'Hamza'
df.drop(index = df[filt].index, inplace = True)

In [ ]:
filt = df['city'] == "Karachi"
df.drop(index = df[filt].index, inplace = True)

In [ ]:
df

,first_name,last_name,age,city,marks,full_name,result,age_group,first,last
0,Ali,Khan,18,Lahore,85,Ali Khan,Pass,Adult,Ali,Khan
2,Sara,Raza,19,Lahore,91,Sara Raza,Pass,Adult,Sara,Raza
4,Ayesha,Sheikh,18,Lahore,88,Ayesha Sheikh,Pass,Adult,Ayesha,Sheikh
6,Zain,Ahmed,20,Multan,95,Zain Ahmed,Pass,Teen,Zain,Ahmed
7,Bilal,Ahmed,19,Lahore,82,NaN,NaN,NaN,NaN,NaN
8,Hassan,Rauf,21,Faisalabad,74,NaN,NaN,NaN,NaN,NaN

In [ ]:
filt = (df['city'] == "Lahore") & (df['marks'] < 90)
df.drop(index = df[filt].index, inplace = True)

In [ ]:
df

,first_name,last_name,age,city,marks,full_name,result,age_group,first,last
2,Sara,Raza,19,Lahore,91,Sara Raza,Pass,Adult,Sara,Raza
6,Zain,Ahmed,20,Multan,95,Zain Ahmed,Pass,Teen,Zain,Ahmed
8,Hassan,Rauf,21,Faisalabad,74,NaN,NaN,NaN,NaN,NaN

In [ ]:
filt = (df['age']>=20) & (df['marks']>=75)
df.drop(index = df[filt].index, inplace = True)

In [ ]:
df

,first_name,last_name,age,city,marks,full_name,result,age_group,first,last
2,Sara,Raza,19,Lahore,91,Sara Raza,Pass,Adult,Sara,Raza
8,Hassan,Rauf,21,Faisalabad,74,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd

data = {
    "first_name": ["Ali", "Ahmed", "Sara", "Hamza", "Ayesha", "Usman", "Zain"],
    "last_name": ["Khan", "Malik", "Raza", "Ali", "Sheikh", "Butt", "Ahmed"],
    "age": [18, 20, 19, 21, 18, 22, 20],
    "city": ["Lahore", "Karachi", "Lahore", "Islamabad", "Lahore", "Karachi", "Multan"],
    "marks": [85, 72, 91, 65, 88, 76, 95]
}

df = pd.DataFrame(data)

In [ ]:
df

  first_name last_name  age       city  marks
0        Ali      Khan   18     Lahore     85
1      Ahmed     Malik   20    Karachi     72
2       Sara      Raza   19     Lahore     91
3      Hamza       Ali   21  Islamabad     65
4     Ayesha    Sheikh   18     Lahore     88
5      Usman      Butt   22    Karachi     76
6       Zain     Ahmed   20     Multan     95

In [ ]:
df['full_name'] = df['first_name'] + ' ' + df['last_name']

In [ ]:
df['result'] = df['marks'].apply(lambda x: 'Pass' if x >= 50 else 'Fail')

In [ ]:
filt = df['result'] == 'Fail'
df.drop(index = df[filt].index, inplace = True)

In [ ]:
filt = (df['city'] != 'Lahore') & (df['city'] != 'Karachi')
df.drop(index = df[filt].index, inplace = True)

In [ ]:
df

  first_name last_name  age     city  marks      full_name result
0        Ali      Khan   18   Lahore     85       Ali Khan   Pass
1      Ahmed     Malik   20  Karachi     72    Ahmed Malik   Pass
2       Sara      Raza   19   Lahore     91      Sara Raza   Pass
4     Ayesha    Sheikh   18   Lahore     88  Ayesha Sheikh   Pass
5      Usman      Butt   22  Karachi     76     Usman Butt   Pass

In [ ]:
import pandas as pd

data = {
    "first_name": ["Ali", "Ahmed", "Sara", "Hamza", "Ayesha", "Usman", "Zain"],
    "last_name": ["Khan", "Malik", "Raza", "Ali", "Sheikh", "Butt", "Ahmed"],
    "age": [18, 20, 19, 21, 18, 22, 20],
    "city": ["Lahore", "Karachi", "Lahore", "Islamabad", "Lahore", "Karachi", "Multan"],
    "marks": [85, 72, 91, 65, 88, 76, 95]
}

df = pd.DataFrame(data)

In [ ]:
new_students = pd.DataFrame({
    "first_name": ["Bilal", "Hassan"],
    "last_name": ["Ahmed", "Rauf"],
    "age": [19, 21],
    "city": ["Lahore", "Faisalabad"],
    "marks": [82, 74]
})

In [ ]:
df = pd.concat([df,new_students], ignore_index=True)

In [ ]:
df

   first_name last_name  age        city  marks
0         Ali      Khan   18      Lahore     85
1       Ahmed     Malik   20     Karachi     72
2        Sara      Raza   19      Lahore     91
3       Hamza       Ali   21   Islamabad     65
4      Ayesha    Sheikh   18      Lahore     88
5       Usman      Butt   22     Karachi     76
6        Zain     Ahmed   20      Multan     95
7       Bilal     Ahmed   19      Lahore     82
8      Hassan      Rauf   21  Faisalabad     74
9       Bilal     Ahmed   19      Lahore     82
10     Hassan      Rauf   21  Faisalabad     74

In [ ]:
df["full_name"] = df['first_name'] + ' ' + df['last_name']

In [ ]:
filt = df['marks'] < 75
df.drop(index = df[filt].index, inplace = True)

In [ ]:
df[['full_name','city','marks']]

       full_name     city  marks
0       Ali Khan   Lahore     85
2      Sara Raza   Lahore     91
4  Ayesha Sheikh   Lahore     88
5     Usman Butt  Karachi     76
6     Zain Ahmed   Multan     95
7    Bilal Ahmed   Lahore     82
9    Bilal Ahmed   Lahore     82