<a href="https://colab.research.google.com/github/MuhammadRayasat/Python_Pandas/blob/main/Lecture_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Round 1 — Basic DataFrame**

In [ ]:
import pandas as pd

data = {
    "name": ["Ali", "Ahmed", "Sara", "Hamza", "Ayesha", "Usman", "Zain"],
    "age": [18, 20, 19, 21, 18, 22, 20],
    "city": ["Lahore", "Karachi", "Lahore", "Islamabad", "Lahore", "Karachi", "Multan"],
    "marks": [85, 72, 91, 65, 88, 76, 95],
    "passed": [True, True, True, False, True, True, True]
}

df = pd.DataFrame(data)

In [ ]:
df.head(5) #First Five rows

     name  age       city  marks  passed
0     Ali   18     Lahore     85    True
1   Ahmed   20    Karachi     72    True
2    Sara   19     Lahore     91    True
3   Hamza   21  Islamabad     65   False
4  Ayesha   18     Lahore     88    True

In [ ]:
df['name'] #Only name Column

0       Ali
1     Ahmed
2      Sara
3     Hamza
4    Ayesha
5     Usman
6      Zain
Name: name, dtype: object

In [ ]:
df[['name','marks']] #Display Name and marks column

     name  marks
0     Ali     85
1   Ahmed     72
2    Sara     91
3   Hamza     65
4  Ayesha     88
5   Usman     76
6    Zain     95

In [ ]:
df.set_index('name', inplace=True) #Set name as index

In [ ]:
df

        age       city  marks  passed
name
Ali      18     Lahore     85    True
Ahmed    20    Karachi     72    True
Sara     19     Lahore     91    True
Hamza    21  Islamabad     65   False
Ayesha   18     Lahore     88    True
Usman    22    Karachi     76    True
Zain     20     Multan     95    True

In [ ]:
df.reset_index(inplace = True) #Reset Index

In [ ]:
df

     name  age       city  marks  passed
0     Ali   18     Lahore     85    True
1   Ahmed   20    Karachi     72    True
2    Sara   19     Lahore     91    True
3   Hamza   21  Islamabad     65   False
4  Ayesha   18     Lahore     88    True
5   Usman   22    Karachi     76    True
6    Zain   20     Multan     95    True

***Round_2:   Filtering***

In [ ]:
filt = df['marks']>80 #Find all students marks > 80
df.loc[filt]

     name  age    city  marks  passed
0     Ali   18  Lahore     85    True
2    Sara   19  Lahore     91    True
4  Ayesha   18  Lahore     88    True
6    Zain   20  Multan     95    True

In [ ]:
filt = df['age']==18 #Find students have age 18
df.loc[filt]

     name  age    city  marks  passed
0     Ali   18  Lahore     85    True
4  Ayesha   18  Lahore     88    True

In [ ]:
df.loc[df['city']=='Lahore'] #Students from lahore

     name  age    city  marks  passed
0     Ali   18  Lahore     85    True
2    Sara   19  Lahore     91    True
4  Ayesha   18  Lahore     88    True

In [ ]:
filt = (df['city']=='Lahore') & (df['marks'] > 85) #From Lahore and marks more then 85
df.loc[filt]

     name  age    city  marks  passed
2    Sara   19  Lahore     91    True
4  Ayesha   18  Lahore     88    True

In [ ]:
df.loc[(df["marks"]<70) | (df["marks"]>90)] #Marks less then 70 or greater then 90

    name  age       city  marks  passed
2   Sara   19     Lahore     91    True
3  Hamza   21  Islamabad     65   False
6   Zain   20     Multan     95    True

***Round 3 — Updating***

In [ ]:
df

     name  age       city  marks  passed
0     Ali   18     Lahore     85    True
1   Ahmed   20    Karachi     72    True
2    Sara   19     Lahore     91    True
3   Hamza   21  Islamabad     65   False
4  Ayesha   18     Lahore     88    True
5   Usman   22    Karachi     76    True
6    Zain   20     Multan     95    True

In [ ]:
df.loc[df['name'] == 'Ali','marks'] = 90 #Ali's Marks change 85 to 90

In [ ]:
df.loc[df['name'] == 'Hamza','passed'] = True #Hamza's passed value True from False

In [ ]:
df['marks'] = df['marks'].apply(lambda x: x+5) #Increase marks by 5

In [ ]:
df

     name  age       city  marks  passed
0     Ali   18     Lahore     95    True
1   Ahmed   20    Karachi     77    True
2    Sara   19     Lahore     96    True
3   Hamza   21  Islamabad     70    True
4  Ayesha   18     Lahore     93    True
5   Usman   22    Karachi     81    True
6    Zain   20     Multan    100    True

In [ ]:
#Changing Zain's city from Multan to Lahore
df.loc[df['name']=='Zain','city'] = 'Lahore'
df

     name  age       city  marks  passed
0     Ali   18     Lahore     95    True
1   Ahmed   20    Karachi     77    True
2    Sara   19     Lahore     96    True
3   Hamza   21  Islamabad     70    True
4  Ayesha   18     Lahore     93    True
5   Usman   22    Karachi     81    True
6    Zain   20     Lahore    100    True

In [ ]:
#Q15
filt = (df['city']=='Lahore') & (df['age'] >= 18) & (df['marks'] >= 85)
df.loc[filt]

     name  age    city  marks  passed
0     Ali   18  Lahore     95    True
2    Sara   19  Lahore     96    True
4  Ayesha   18  Lahore     93    True
6    Zain   20  Lahore    100    True

In [ ]:
#Q16
df.loc[df['marks']==95]

  name  age    city  marks  passed
0  Ali   18  Lahore     95    True

In [ ]:
df

     name  age       city  marks  passed
0     Ali   18     Lahore     95    True
1   Ahmed   20    Karachi     77    True
2    Sara   19     Lahore     96    True
3   Hamza   21  Islamabad     70    True
4  Ayesha   18     Lahore     93    True
5   Usman   22    Karachi     81    True
6    Zain   20     Lahore    100    True

In [ ]:
#Q17
df.loc[df['city']=='Karachi','marks'] = df.loc[df['city']=='Karachi','marks'].apply(lambda x: x+3)

In [ ]:
df

     name  age       city  marks  passed
0     Ali   18     Lahore     95    True
1   Ahmed   20    Karachi     80    True
2    Sara   19     Lahore     96    True
3   Hamza   21  Islamabad     70    True
4  Ayesha   18     Lahore     93    True
5   Usman   22    Karachi     84    True
6    Zain   20     Lahore    100    True

In [ ]:
#Q18
df.loc[df['passed'] == True , 'name']

0       Ali
1     Ahmed
2      Sara
3     Hamza
4    Ayesha
5     Usman
6      Zain
Name: name, dtype: object