<a href="https://colab.research.google.com/github/MuhammadRayasat/Python_Pandas/blob/main/Lecture_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
    "name": ["Ali", "Ahmed", "Sara", "Hamza", "Ayesha", "Usman", "Zain", "Bilal"],
    "age": [18, 20, 19, 21, 18, 22, 20, 19],
    "city": ["Lahore", "Karachi", "Lahore", "Islamabad",
             "Lahore", "Karachi", "Multan", "Lahore"],
    "marks": [85, 72, 91, 65, 88, 76, 95, 72],
    "attendance": [90, 85, 95, 70, 92, 88, 98, 80]
}

df = pd.DataFrame(data)

In [2]:
df=df.sort_values(by="marks")

In [3]:
df

     name  age       city  marks  attendance
3   Hamza   21  Islamabad     65          70
1   Ahmed   20    Karachi     72          85
7   Bilal   19     Lahore     72          80
5   Usman   22    Karachi     76          88
0     Ali   18     Lahore     85          90
4  Ayesha   18     Lahore     88          92
2    Sara   19     Lahore     91          95
6    Zain   20     Multan     95          98

In [4]:
df = df.sort_values(by="marks", ascending=False)

In [5]:
df

     name  age       city  marks  attendance
6    Zain   20     Multan     95          98
2    Sara   19     Lahore     91          95
4  Ayesha   18     Lahore     88          92
0     Ali   18     Lahore     85          90
5   Usman   22    Karachi     76          88
1   Ahmed   20    Karachi     72          85
7   Bilal   19     Lahore     72          80
3   Hamza   21  Islamabad     65          70

In [6]:
df = df.sort_values(by="age")

In [7]:
df

     name  age       city  marks  attendance
0     Ali   18     Lahore     85          90
4  Ayesha   18     Lahore     88          92
2    Sara   19     Lahore     91          95
7   Bilal   19     Lahore     72          80
6    Zain   20     Multan     95          98
1   Ahmed   20    Karachi     72          85
3   Hamza   21  Islamabad     65          70
5   Usman   22    Karachi     76          88

In [8]:
df = df.sort_values(by="age", ascending=False)

In [9]:
df

     name  age       city  marks  attendance
5   Usman   22    Karachi     76          88
3   Hamza   21  Islamabad     65          70
6    Zain   20     Multan     95          98
1   Ahmed   20    Karachi     72          85
2    Sara   19     Lahore     91          95
7   Bilal   19     Lahore     72          80
0     Ali   18     Lahore     85          90
4  Ayesha   18     Lahore     88          92

In [10]:
df = df.sort_values(by="city")

In [11]:
df

     name  age       city  marks  attendance
3   Hamza   21  Islamabad     65          70
5   Usman   22    Karachi     76          88
1   Ahmed   20    Karachi     72          85
2    Sara   19     Lahore     91          95
7   Bilal   19     Lahore     72          80
0     Ali   18     Lahore     85          90
4  Ayesha   18     Lahore     88          92
6    Zain   20     Multan     95          98

Multiple Columns

In [12]:
df.sort_values(by=["city", "marks"], ascending=[True, False], inplace=True)

In [13]:
df

     name  age       city  marks  attendance
3   Hamza   21  Islamabad     65          70
5   Usman   22    Karachi     76          88
1   Ahmed   20    Karachi     72          85
2    Sara   19     Lahore     91          95
4  Ayesha   18     Lahore     88          92
0     Ali   18     Lahore     85          90
7   Bilal   19     Lahore     72          80
6    Zain   20     Multan     95          98

In [14]:
df.sort_values(by= ["age", "marks"], ascending = [True, False], inplace = True)

In [15]:
df

     name  age       city  marks  attendance
4  Ayesha   18     Lahore     88          92
0     Ali   18     Lahore     85          90
2    Sara   19     Lahore     91          95
7   Bilal   19     Lahore     72          80
6    Zain   20     Multan     95          98
1   Ahmed   20    Karachi     72          85
3   Hamza   21  Islamabad     65          70
5   Usman   22    Karachi     76          88

In [16]:
df.sort_values(by = ["marks", "name"], ascending = [False, True], inplace = True)

In [17]:
df

     name  age       city  marks  attendance
6    Zain   20     Multan     95          98
2    Sara   19     Lahore     91          95
4  Ayesha   18     Lahore     88          92
0     Ali   18     Lahore     85          90
5   Usman   22    Karachi     76          88
1   Ahmed   20    Karachi     72          85
7   Bilal   19     Lahore     72          80
3   Hamza   21  Islamabad     65          70

In [18]:
df.set_index("name", inplace = True)

In [19]:
df.sort_index(inplace = True)

In [20]:
df

        age       city  marks  attendance
name
Ahmed    20    Karachi     72          85
Ali      18     Lahore     85          90
Ayesha   18     Lahore     88          92
Bilal    19     Lahore     72          80
Hamza    21  Islamabad     65          70
Sara     19     Lahore     91          95
Usman    22    Karachi     76          88
Zain     20     Multan     95          98

In [21]:
df.sort_index(inplace = True, ascending = False)

In [22]:
df

        age       city  marks  attendance
name
Zain     20     Multan     95          98
Usman    22    Karachi     76          88
Sara     19     Lahore     91          95
Hamza    21  Islamabad     65          70
Bilal    19     Lahore     72          80
Ayesha   18     Lahore     88          92
Ali      18     Lahore     85          90
Ahmed    20    Karachi     72          85

In [23]:
df.nlargest(3, "marks")

        age    city  marks  attendance
name
Zain     20  Multan     95          98
Sara     19  Lahore     91          95
Ayesha   18  Lahore     88          92

In [24]:
df.nsmallest(3, "marks")

       age       city  marks  attendance
name
Hamza   21  Islamabad     65          70
Bilal   19     Lahore     72          80
Ahmed   20    Karachi     72          85

In [25]:
df.nlargest(5, "attendance")

        age     city  marks  attendance
name
Zain     20   Multan     95          98
Sara     19   Lahore     91          95
Ayesha   18   Lahore     88          92
Ali      18   Lahore     85          90
Usman    22  Karachi     76          88

In [26]:
df.nsmallest(2,"age")

        age    city  marks  attendance
name
Ayesha   18  Lahore     88          92
Ali      18  Lahore     85          90

In [27]:
df.reset_index(inplace = True)

Challenge

In [28]:
filt = ["name","city","marks","attendance"]
df[filt].nlargest(3, "marks")

     name    city  marks  attendance
0    Zain  Multan     95          98
2    Sara  Lahore     91          95
5  Ayesha  Lahore     88          92

In [29]:
df.nlargest(4, "attendance").sort_values(by="marks", ascending=False)

     name  age    city  marks  attendance
0    Zain   20  Multan     95          98
2    Sara   19  Lahore     91          95
5  Ayesha   18  Lahore     88          92
6     Ali   18  Lahore     85          90

In [30]:
df[["name","marks","age","attendance"]].nlargest(3, "marks")

     name  marks  age  attendance
0    Zain     95   20          98
2    Sara     91   19          95
5  Ayesha     88   18          92